// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3fvIZBYVs1WMJTLmEImDniRjvAJyvznw',
    appId: '1:946754431085:web:3d455250765af891a4b764',
    messagingSenderId: '946754431085',
    projectId: 'wordle-1ac87',
    authDomain: 'wordle-1ac87.firebaseapp.com',
    storageBucket: 'wordle-1ac87.appspot.com',
    measurementId: 'G-C3QFGJMQPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBFvMXhoTafUGP4WWK0d24Y2jK10EJ3vU',
    appId: '1:946754431085:android:1b6ba2bd4de39f35a4b764',
    messagingSenderId: '946754431085',
    projectId: 'wordle-1ac87',
    storageBucket: 'wordle-1ac87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDxB1qx-_NSVK3UQIeRp4JLJTrT6pwJo',
    appId: '1:946754431085:ios:19f0c044fe2dbe7da4b764',
    messagingSenderId: '946754431085',
    projectId: 'wordle-1ac87',
    storageBucket: 'wordle-1ac87.appspot.com',
    androidClientId: '946754431085-jresc2vf77sdaocc949q8n0run51jqve.apps.googleusercontent.com',
    iosClientId: '946754431085-tt3nca0rrp7ggnfqd6tdhsmkrdvbvmd0.apps.googleusercontent.com',
    iosBundleId: 'com.samurais.wordle',
  );
}
